

DBSync3 : Check.cs DBSync3.cs Index.cs  ParsePostgres.cs \
	  Column.cs   FileRead.cs    ISchemaElement.cs  Schema.cs \
	  Comment.cs  ForeignKey.cs  ParseMicrosoft.cs  Table.cs
	gmcs -out:$@.exe $^
	mv $@.exe $@
